import * as Blockly from 'blockly';
import { PythonGenerator } from 'blockly/python';
import { registerProjectGenerators } from './project';
import { registerGpioGenerators } from './gpio';
import { registerTimingGenerators } from './timing';
import { registerMotorGenerators } from './motors';
import { registerIotGenerators } from './iot';
import { registerDisplayGenerators } from './display';
import { registerNetlogicGenerators } from './netlogic';

export const micropythonGenerator = new PythonGenerator('MicroPython');

export function registerAllGenerators() {
  registerProjectGenerators(micropythonGenerator);
  registerGpioGenerators(micropythonGenerator);
  registerTimingGenerators(micropythonGenerator);
  registerMotorGenerators(micropythonGenerator);
  registerIotGenerators(micropythonGenerator);
  registerDisplayGenerators(micropythonGenerator);
  registerNetlogicGenerators(micropythonGenerator);
}

export function generateMicroPython(workspace: Blockly.Workspace): string {
  const rawCode = micropythonGenerator.workspaceToCode(workspace);
  const imports = collectImports(workspace);
  const header = [
    '# Generated by Geneo IoT',
    '# Target: ESP32 MicroPython',
    '',
    ...imports,
    '',
  ].join('\n');
  return header + rawCode;
}

function collectImports(workspace: Blockly.Workspace): string[] {
  const blocks = workspace.getAllBlocks(false);
  const imports = new Set<string>();

  for (const block of blocks) {
    switch (block.type) {
      case 'gpio_set_pin_mode':
      case 'gpio_digital_write':
      case 'gpio_digital_read':
      case 'gpio_analog_read':
        imports.add('import machine');
        break;
      case 'timing_wait':
        imports.add('import time');
        break;
      case 'motor_servo_set_angle':
        imports.add('import machine');
        imports.add('from machine import PWM');
        break;
      case 'iot_wifi_connect':
        imports.add('import network');
        break;
      case 'iot_mqtt_connect':
      case 'iot_mqtt_publish':
        imports.add('from umqtt.simple import MQTTClient');
        break;
      case 'iot_http_get':
        imports.add('import urequests');
        break;
      case 'display_oled_init':
      case 'display_oled_text':
      case 'display_oled_clear':
        imports.add('import machine');
        imports.add('import ssd1306');
        imports.add('from machine import Pin, I2C');
        break;
    }
  }
  return Array.from(imports);
}
